<?php

namespace AppBundle\Repository;

/**
 * area_expertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class area_expertiseRepository extends \Doctrine\ORM\EntityRepository
{
}
