<?php

namespace AppBundle\Repository;

/**
 * certificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class certificationRepository extends \Doctrine\ORM\EntityRepository
{
}
