<?php

namespace AppBundle\Repository;

/**
 * experience_occupationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class experience_occupationRepository extends \Doctrine\ORM\EntityRepository
{
}
