<?php

namespace AppBundle\Repository;

/**
 * expertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expertiseRepository extends \Doctrine\ORM\EntityRepository
{
}
