<?php

namespace AppBundle\Repository;

/**
 * field_experienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class field_experienceRepository extends \Doctrine\ORM\EntityRepository
{
}
