<?php

namespace AppBundle\Repository;

/**
 * gradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gradeRepository extends \Doctrine\ORM\EntityRepository
{
}
