<?php

namespace AppBundle\Repository;

/**
 * software_expRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class software_expRepository extends \Doctrine\ORM\EntityRepository
{
}
