<?php

namespace AppBundle\Repository;

/**
 * softwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class softwareRepository extends \Doctrine\ORM\EntityRepository
{
}
