<?php

namespace odisVendorBundle\Repository;

/**
 * vendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vendorRepository extends \Doctrine\ORM\EntityRepository
{
}
